branch-defaults:
  mvp:
    environment: barkda-api-mvp
environment-defaults:
  barkda-api-mvp:
    branch: null
    repository: null
global:
  application_name: jayvee-personal-web
  default_ec2_keyname: general-key
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Node.js running on
    64bit Amazon Linux/4.4.0
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
